\documentclass[]{article}
\usepackage{lmodern}
\usepackage{amssymb,amsmath}
\usepackage{ifxetex,ifluatex}
\usepackage{fixltx2e} % provides \textsubscript
\ifnum 0\ifxetex 1\fi\ifluatex 1\fi=0 % if pdftex
  \usepackage[T1]{fontenc}
  \usepackage[utf8]{inputenc}
\else % if luatex or xelatex
  \ifxetex
    \usepackage{mathspec}
  \else
    \usepackage{fontspec}
  \fi
  \defaultfontfeatures{Ligatures=TeX,Scale=MatchLowercase}
\fi
% use upquote if available, for straight quotes in verbatim environments
\IfFileExists{upquote.sty}{\usepackage{upquote}}{}
% use microtype if available
\IfFileExists{microtype.sty}{%
\usepackage{microtype}
\UseMicrotypeSet[protrusion]{basicmath} % disable protrusion for tt fonts
}{}
\usepackage[margin=1in]{geometry}
\usepackage{hyperref}
\hypersetup{unicode=true,
            pdfborder={0 0 0},
            breaklinks=true}
\urlstyle{same}  % don't use monospace font for urls
\usepackage{color}
\usepackage{fancyvrb}
\newcommand{\VerbBar}{|}
\newcommand{\VERB}{\Verb[commandchars=\\\{\}]}
\DefineVerbatimEnvironment{Highlighting}{Verbatim}{commandchars=\\\{\}}
% Add ',fontsize=\small' for more characters per line
\usepackage{framed}
\definecolor{shadecolor}{RGB}{248,248,248}
\newenvironment{Shaded}{\begin{snugshade}}{\end{snugshade}}
\newcommand{\AlertTok}[1]{\textcolor[rgb]{0.94,0.16,0.16}{#1}}
\newcommand{\AnnotationTok}[1]{\textcolor[rgb]{0.56,0.35,0.01}{\textbf{\textit{#1}}}}
\newcommand{\AttributeTok}[1]{\textcolor[rgb]{0.77,0.63,0.00}{#1}}
\newcommand{\BaseNTok}[1]{\textcolor[rgb]{0.00,0.00,0.81}{#1}}
\newcommand{\BuiltInTok}[1]{#1}
\newcommand{\CharTok}[1]{\textcolor[rgb]{0.31,0.60,0.02}{#1}}
\newcommand{\CommentTok}[1]{\textcolor[rgb]{0.56,0.35,0.01}{\textit{#1}}}
\newcommand{\CommentVarTok}[1]{\textcolor[rgb]{0.56,0.35,0.01}{\textbf{\textit{#1}}}}
\newcommand{\ConstantTok}[1]{\textcolor[rgb]{0.00,0.00,0.00}{#1}}
\newcommand{\ControlFlowTok}[1]{\textcolor[rgb]{0.13,0.29,0.53}{\textbf{#1}}}
\newcommand{\DataTypeTok}[1]{\textcolor[rgb]{0.13,0.29,0.53}{#1}}
\newcommand{\DecValTok}[1]{\textcolor[rgb]{0.00,0.00,0.81}{#1}}
\newcommand{\DocumentationTok}[1]{\textcolor[rgb]{0.56,0.35,0.01}{\textbf{\textit{#1}}}}
\newcommand{\ErrorTok}[1]{\textcolor[rgb]{0.64,0.00,0.00}{\textbf{#1}}}
\newcommand{\ExtensionTok}[1]{#1}
\newcommand{\FloatTok}[1]{\textcolor[rgb]{0.00,0.00,0.81}{#1}}
\newcommand{\FunctionTok}[1]{\textcolor[rgb]{0.00,0.00,0.00}{#1}}
\newcommand{\ImportTok}[1]{#1}
\newcommand{\InformationTok}[1]{\textcolor[rgb]{0.56,0.35,0.01}{\textbf{\textit{#1}}}}
\newcommand{\KeywordTok}[1]{\textcolor[rgb]{0.13,0.29,0.53}{\textbf{#1}}}
\newcommand{\NormalTok}[1]{#1}
\newcommand{\OperatorTok}[1]{\textcolor[rgb]{0.81,0.36,0.00}{\textbf{#1}}}
\newcommand{\OtherTok}[1]{\textcolor[rgb]{0.56,0.35,0.01}{#1}}
\newcommand{\PreprocessorTok}[1]{\textcolor[rgb]{0.56,0.35,0.01}{\textit{#1}}}
\newcommand{\RegionMarkerTok}[1]{#1}
\newcommand{\SpecialCharTok}[1]{\textcolor[rgb]{0.00,0.00,0.00}{#1}}
\newcommand{\SpecialStringTok}[1]{\textcolor[rgb]{0.31,0.60,0.02}{#1}}
\newcommand{\StringTok}[1]{\textcolor[rgb]{0.31,0.60,0.02}{#1}}
\newcommand{\VariableTok}[1]{\textcolor[rgb]{0.00,0.00,0.00}{#1}}
\newcommand{\VerbatimStringTok}[1]{\textcolor[rgb]{0.31,0.60,0.02}{#1}}
\newcommand{\WarningTok}[1]{\textcolor[rgb]{0.56,0.35,0.01}{\textbf{\textit{#1}}}}
\usepackage{graphicx,grffile}
\makeatletter
\def\maxwidth{\ifdim\Gin@nat@width>\linewidth\linewidth\else\Gin@nat@width\fi}
\def\maxheight{\ifdim\Gin@nat@height>\textheight\textheight\else\Gin@nat@height\fi}
\makeatother
% Scale images if necessary, so that they will not overflow the page
% margins by default, and it is still possible to overwrite the defaults
% using explicit options in \includegraphics[width, height, ...]{}
\setkeys{Gin}{width=\maxwidth,height=\maxheight,keepaspectratio}
\IfFileExists{parskip.sty}{%
\usepackage{parskip}
}{% else
\setlength{\parindent}{0pt}
\setlength{\parskip}{6pt plus 2pt minus 1pt}
}
\setlength{\emergencystretch}{3em}  % prevent overfull lines
\providecommand{\tightlist}{%
  \setlength{\itemsep}{0pt}\setlength{\parskip}{0pt}}
\setcounter{secnumdepth}{0}
% Redefines (sub)paragraphs to behave more like sections
\ifx\paragraph\undefined\else
\let\oldparagraph\paragraph
\renewcommand{\paragraph}[1]{\oldparagraph{#1}\mbox{}}
\fi
\ifx\subparagraph\undefined\else
\let\oldsubparagraph\subparagraph
\renewcommand{\subparagraph}[1]{\oldsubparagraph{#1}\mbox{}}
\fi

%%% Use protect on footnotes to avoid problems with footnotes in titles
\let\rmarkdownfootnote\footnote%
\def\footnote{\protect\rmarkdownfootnote}

%%% Change title format to be more compact
\usepackage{titling}

% Create subtitle command for use in maketitle
\providecommand{\subtitle}[1]{
  \posttitle{
    \begin{center}\large#1\end{center}
    }
}

\setlength{\droptitle}{-2em}

  \title{}
    \pretitle{\vspace{\droptitle}}
  \posttitle{}
    \author{}
    \preauthor{}\postauthor{}
    \date{}
    \predate{}\postdate{}
  

\begin{document}

\hypertarget{lab-report-number-1}{%
\subsection{Lab Report Number 1}\label{lab-report-number-1}}

\hypertarget{option-1-run-a-trend-analysis}{%
\subsection{Option 1: Run a trend
analysis}\label{option-1-run-a-trend-analysis}}

I am going to look at the trends in people's worry about losing their
jobs. Specifically, respondents are asked: ``Thinking about the next 12
months, how likely do you think it is that you will lose your job or be
laid off -- very likely, fairly likely, not too likely, or not at all
likely? (1) Very likely, (2) Fairly likely, (3) Not too likely, (4) Not
at all likely?''

\hypertarget{install-packages-and-open-gsstrends.csv}{%
\subsection{Install packages and open
GSStrends.csv}\label{install-packages-and-open-gsstrends.csv}}

\begin{Shaded}
\begin{Highlighting}[]
\KeywordTok{library}\NormalTok{(data.table)}
\KeywordTok{library}\NormalTok{(QMSS)}
\NormalTok{vars <-}\StringTok{ }\KeywordTok{c}\NormalTok{(}\StringTok{"joblose"}\NormalTok{, }\StringTok{"year"}\NormalTok{, }\StringTok{"degree"}\NormalTok{)  }\CommentTok{## I am going to look at year and education}
\NormalTok{sub =}\StringTok{ }\NormalTok{data.table}\OperatorTok{::}\KeywordTok{fread}\NormalTok{(}\StringTok{"/Users/hengyuai/Desktop/TS/Lab1/trends-gss.csv"}\NormalTok{,}
                        \DataTypeTok{sep =} \StringTok{","}\NormalTok{,}
                        \DataTypeTok{select =}\NormalTok{ vars)}
\KeywordTok{library}\NormalTok{(plyr)}
\KeywordTok{library}\NormalTok{(ggplot2)}
\end{Highlighting}
\end{Shaded}

\hypertarget{recode-variables-to-make-it-easier-to-interpret}{%
\subsection{Recode variables to make it easier to
interpret}\label{recode-variables-to-make-it-easier-to-interpret}}

\begin{Shaded}
\begin{Highlighting}[]
\NormalTok{sub =}\StringTok{ }\KeywordTok{na.omit}\NormalTok{(sub) }\CommentTok{## the analysis will require complete cases and no missings on any of these values}
\NormalTok{sub}\OperatorTok{$}\NormalTok{worry =}\StringTok{ }\KeywordTok{ifelse}\NormalTok{(sub}\OperatorTok{$}\NormalTok{joblose }\OperatorTok{<=}\StringTok{ }\DecValTok{2}\NormalTok{, }\DecValTok{1}\NormalTok{, }\DecValTok{0}\NormalTok{) }\CommentTok{## recode "jobloss", it is 1 if you are worried about losing your job}
\NormalTok{sub[sub}\OperatorTok{$}\NormalTok{degree }\OperatorTok{<}\StringTok{ }\DecValTok{5}\NormalTok{] }\CommentTok{## delete the "DK" and "NA" answer in the degree column}
\NormalTok{sub}\OperatorTok{$}\NormalTok{hiedu =}\StringTok{ }\KeywordTok{ifelse}\NormalTok{(sub}\OperatorTok{$}\NormalTok{degree }\OperatorTok{>=}\StringTok{ }\DecValTok{3}\NormalTok{, }\DecValTok{1}\NormalTok{, }\DecValTok{0}\NormalTok{) }\CommentTok{## recode "degree", you got higher education if you received a bachelor or graduate degree}
\end{Highlighting}
\end{Shaded}

\hypertarget{show-the-distribution-of-the-answer}{%
\subsection{Show the distribution of the
answer}\label{show-the-distribution-of-the-answer}}

\begin{Shaded}
\begin{Highlighting}[]
\KeywordTok{Tab}\NormalTok{(sub}\OperatorTok{$}\NormalTok{worry)}
\end{Highlighting}
\end{Shaded}

\begin{verbatim}
##   Count   Pct Cum.Pct
## 0 16708 89.14   89.14
## 1  2036 10.86  100.00
\end{verbatim}

This indicates that for all of the years, about 10.86\% of respondents
were worried about losing their jobs (Answer \#1 and \#2).

\hypertarget{get-mean-of-n.natcrime-by-year-using-ddply-from-plyr-package}{%
\subsection{Get mean of n.natcrime by year using ddply from plyr
package}\label{get-mean-of-n.natcrime-by-year-using-ddply-from-plyr-package}}

\begin{Shaded}
\begin{Highlighting}[]
\NormalTok{by.year =}\StringTok{ }\KeywordTok{ddply}\NormalTok{(sub, }\StringTok{"year"}\NormalTok{, summarise, }\DataTypeTok{mean =} \KeywordTok{mean}\NormalTok{(worry))}
\NormalTok{\{}\KeywordTok{plot}\NormalTok{(by.year, }\DataTypeTok{type =} \StringTok{"l"}\NormalTok{, }\DataTypeTok{lwd =} \DecValTok{2}\NormalTok{, }\DataTypeTok{col =} \StringTok{"navyblue"}\NormalTok{, }\DataTypeTok{bty =}\StringTok{"l"}\NormalTok{) }\CommentTok{## plot the trend}
\KeywordTok{with}\NormalTok{(by.year, }\KeywordTok{abline}\NormalTok{(}\KeywordTok{line}\NormalTok{(year, mean), }\DataTypeTok{col =} \StringTok{"maroon"}\NormalTok{, }\DataTypeTok{lwd =} \DecValTok{2}\NormalTok{, }\DataTypeTok{lty =} \DecValTok{2}\NormalTok{))\} }\CommentTok{## add a fitted line }
\end{Highlighting}
\end{Shaded}

\includegraphics{Lab-1_do_files/figure-latex/unnamed-chunk-5-1.pdf}

From the graph, we can clearly see that the extent of people's worry
about losing job has changed across time. People were less worried in
the earlier period, from roughly 1973 until the 2002. After 2005, people
became more pessimistic about their jobs.

\hypertarget{ols-regression}{%
\subsection{OLS Regression}\label{ols-regression}}

I would like to develop a regression model that would capture the
dynamics of people's worry about their jobs. As a default, I will fit a
linear model, where year is entered in as a linear term. The model is
below:

\begin{Shaded}
\begin{Highlighting}[]
\NormalTok{lm.worry1 =}\StringTok{ }\KeywordTok{lm}\NormalTok{(worry }\OperatorTok{~}\StringTok{ }\NormalTok{year, sub)}
\KeywordTok{summary}\NormalTok{(lm.worry1)}
\end{Highlighting}
\end{Shaded}

\begin{verbatim}
## 
## Call:
## lm(formula = worry ~ year, data = sub)
## 
## Residuals:
##     Min      1Q  Median      3Q     Max 
## -0.1131 -0.1101 -0.1083 -0.1058  0.8957 
## 
## Coefficients:
##               Estimate Std. Error t value Pr(>|t|)
## (Intercept) -0.3902785  0.4485946  -0.870    0.384
## year         0.0002502  0.0002250   1.112    0.266
## 
## Residual standard error: 0.3112 on 18742 degrees of freedom
## Multiple R-squared:  6.599e-05,  Adjusted R-squared:  1.264e-05 
## F-statistic: 1.237 on 1 and 18742 DF,  p-value: 0.2661
\end{verbatim}

This model shows that with each year that passes, people's worry
increased, on average, by 0.000247 points ; it is not statistically
significant (p \textgreater{} 0.1). The Adjusted Rsquared from this
model is 6.432e-05, which is quite low. Also, in the graph above, it is
not hard to see that the linear fit line misses most of the ups and
downs of the trend.

\hypertarget{consider-a-quadratic-fit}{%
\subsection{Consider a quadratic fit}\label{consider-a-quadratic-fit}}

\begin{Shaded}
\begin{Highlighting}[]
\NormalTok{lm.worry2 =}\StringTok{ }\KeywordTok{lm}\NormalTok{(worry }\OperatorTok{~}\StringTok{ }\NormalTok{year }\OperatorTok{+}\StringTok{ }\KeywordTok{I}\NormalTok{(year}\OperatorTok{^}\DecValTok{2}\NormalTok{), sub)}
\KeywordTok{summary}\NormalTok{(lm.worry2)}
\end{Highlighting}
\end{Shaded}

\begin{verbatim}
## 
## Call:
## lm(formula = worry ~ year + I(year^2), data = sub)
## 
## Residuals:
##     Min      1Q  Median      3Q     Max 
## -0.1257 -0.1137 -0.1054 -0.1026  0.8976 
## 
## Coefficients:
##               Estimate Std. Error t value Pr(>|t|)   
## (Intercept)  2.358e+02  9.077e+01   2.598  0.00938 **
## year        -2.366e-01  9.103e-02  -2.600  0.00934 **
## I(year^2)    5.939e-05  2.282e-05   2.602  0.00926 **
## ---
## Signif. codes:  0 '***' 0.001 '**' 0.01 '*' 0.05 '.' 0.1 ' ' 1
## 
## Residual standard error: 0.3111 on 18741 degrees of freedom
## Multiple R-squared:  0.0004272,  Adjusted R-squared:  0.0003205 
## F-statistic: 4.005 on 2 and 18741 DF,  p-value: 0.01824
\end{verbatim}

In the quadratic model, the Rsquared increases to 0.0004009, suggesting
that we can explain about 0.02 percent of the variation in people's
worry with our time trend, better than the linear trend model.

\hypertarget{consider-a-cubic-fit}{%
\subsection{Consider a cubic fit}\label{consider-a-cubic-fit}}

\begin{Shaded}
\begin{Highlighting}[]
\NormalTok{lm.worry3 =}\StringTok{ }\KeywordTok{lm}\NormalTok{(worry }\OperatorTok{~}\StringTok{ }\NormalTok{year }\OperatorTok{+}\StringTok{ }\KeywordTok{I}\NormalTok{(year}\OperatorTok{^}\DecValTok{2}\NormalTok{) }\OperatorTok{+}\StringTok{ }\KeywordTok{I}\NormalTok{(year}\OperatorTok{^}\DecValTok{3}\NormalTok{), sub)}
\KeywordTok{summary}\NormalTok{(lm.worry3)}
\end{Highlighting}
\end{Shaded}

\begin{verbatim}
## 
## Call:
## lm(formula = worry ~ year + I(year^2) + I(year^3), data = sub)
## 
## Residuals:
##      Min       1Q   Median       3Q      Max 
## -0.14372 -0.11364 -0.10488 -0.09849  0.90254 
## 
## Coefficients:
##               Estimate Std. Error t value Pr(>|t|)    
## (Intercept) -6.948e+04  1.943e+04  -3.576 0.000350 ***
## year         1.046e+02  2.923e+01   3.580 0.000344 ***
## I(year^2)   -5.253e-02  1.466e-02  -3.584 0.000339 ***
## I(year^3)    8.791e-06  2.450e-06   3.588 0.000334 ***
## ---
## Signif. codes:  0 '***' 0.001 '**' 0.01 '*' 0.05 '.' 0.1 ' ' 1
## 
## Residual standard error: 0.311 on 18740 degrees of freedom
## Multiple R-squared:  0.001114,   Adjusted R-squared:  0.0009536 
## F-statistic: 6.964 on 3 and 18740 DF,  p-value: 0.0001115
\end{verbatim}

In the cubic model, the Rsquared increases to 0.001111, suggesting that
we can explain about 0.033 percent of the variation in concern for crime
with our time trend, better than the linear trend model and the
quadratic model

\hypertarget{graph-the-cubic-trend}{%
\subsection{Graph the cubic trend}\label{graph-the-cubic-trend}}

\begin{Shaded}
\begin{Highlighting}[]
\NormalTok{by.year.q =}\StringTok{ }\KeywordTok{ggplot}\NormalTok{(by.year, }\KeywordTok{aes}\NormalTok{(}\DataTypeTok{x =}\NormalTok{ year, }\DataTypeTok{y =}\NormalTok{ mean)) }\OperatorTok{+}\StringTok{ }\KeywordTok{geom_line}\NormalTok{(}\DataTypeTok{color =} \StringTok{"navyblue"}\NormalTok{) }\CommentTok{## plot the trend}
\NormalTok{by.year.q }\OperatorTok{+}\StringTok{ }\KeywordTok{stat_smooth}\NormalTok{(}\DataTypeTok{methiod =} \StringTok{"lm"}\NormalTok{, }\DataTypeTok{formular =}\NormalTok{ y }\OperatorTok{~}\StringTok{ }\KeywordTok{poly}\NormalTok{(x,}\DecValTok{3}\NormalTok{), }\DataTypeTok{color =} \StringTok{"maroon"}\NormalTok{, }\DataTypeTok{se =}\NormalTok{ F, }\DataTypeTok{lty =} \DecValTok{2}\NormalTok{) }\CommentTok{## add a cubic fitted line}
\end{Highlighting}
\end{Shaded}

\begin{verbatim}
## `geom_smooth()` using method = 'loess' and formula 'y ~ x'
\end{verbatim}

\includegraphics{Lab-1_do_files/figure-latex/unnamed-chunk-9-1.pdf}

The graph above shows the trend of people's worry of losing job. This
cubic fit line better catches the ups and downs of the trend than the
linear fit line in the first graph.

\hypertarget{graph-trend-over-time-by-degree}{%
\subsection{Graph trend over time by
degree}\label{graph-trend-over-time-by-degree}}

\begin{Shaded}
\begin{Highlighting}[]
\NormalTok{by.year.edu =}\StringTok{ }\KeywordTok{ddply}\NormalTok{(sub, }\KeywordTok{c}\NormalTok{(}\StringTok{"year"}\NormalTok{, }\StringTok{"hiedu"}\NormalTok{), summarise, }\DataTypeTok{mean =} \KeywordTok{mean}\NormalTok{(worry, }\DataTypeTok{na.rm =}\NormalTok{ T))}
\NormalTok{plot_by_year_edu =}\StringTok{ }\KeywordTok{ggplot}\NormalTok{(by.year.edu, }\KeywordTok{aes}\NormalTok{(}\DataTypeTok{x =}\NormalTok{ year, }\DataTypeTok{y =}\NormalTok{ mean, }\DataTypeTok{group =}\NormalTok{ hiedu, }\DataTypeTok{color =} \KeywordTok{factor}\NormalTok{(hiedu))) }\OperatorTok{+}\StringTok{ }\KeywordTok{geom_point}\NormalTok{() }\OperatorTok{+}\StringTok{ }\KeywordTok{geom_line}\NormalTok{() }\OperatorTok{+}\StringTok{ }\KeywordTok{scale_color_manual}\NormalTok{(}\DataTypeTok{values =} \KeywordTok{c}\NormalTok{(}\StringTok{"navyblue"}\NormalTok{, }\StringTok{"darkmagenta"}\NormalTok{), }\DataTypeTok{labels =} \KeywordTok{c}\NormalTok{(}\StringTok{"not receive high education"}\NormalTok{, }\StringTok{" receive high education"}\NormalTok{), }\DataTypeTok{name =} \StringTok{""}\NormalTok{) }\CommentTok{## plot the trend}
\NormalTok{plot_by_year_edu }\OperatorTok{+}\StringTok{ }\KeywordTok{stat_smooth}\NormalTok{(}\DataTypeTok{method =} \StringTok{"lm"}\NormalTok{, }\DataTypeTok{formula =}\NormalTok{ y }\OperatorTok{~}\StringTok{ }\KeywordTok{poly}\NormalTok{(x,}\DecValTok{3}\NormalTok{), }\DataTypeTok{se =}\NormalTok{ F, }\DataTypeTok{lty =} \DecValTok{2}\NormalTok{) }\CommentTok{# add cubic fit lines}
\end{Highlighting}
\end{Shaded}

\includegraphics{Lab-1_do_files/figure-latex/unnamed-chunk-10-1.pdf}

The graph above is the trend of people's worry of losing job, divided by
their education. We can see that people with high education were less
worried than people with lower education level. But it seems that those
two groups of people follow a very similar pattern.

\hypertarget{run-individual-subsetted-regressions-and-interacted-model}{%
\subsection{Run individual subsetted regressions and interacted
model}\label{run-individual-subsetted-regressions-and-interacted-model}}

\begin{Shaded}
\begin{Highlighting}[]
\NormalTok{lm4 =}\StringTok{ }\KeywordTok{lm}\NormalTok{(worry }\OperatorTok{~}\StringTok{ }\NormalTok{year }\OperatorTok{+}\StringTok{ }\KeywordTok{I}\NormalTok{(year}\OperatorTok{^}\DecValTok{2}\NormalTok{) }\OperatorTok{+}\StringTok{ }\KeywordTok{I}\NormalTok{(year}\OperatorTok{^}\DecValTok{3}\NormalTok{), sub, }\DataTypeTok{subset =}\NormalTok{ hiedu}\OperatorTok{==}\DecValTok{1}\NormalTok{)}
\KeywordTok{summary}\NormalTok{(lm4)}
\end{Highlighting}
\end{Shaded}

\begin{verbatim}
## 
## Call:
## lm(formula = worry ~ year + I(year^2) + I(year^3), data = sub, 
##     subset = hiedu == 1)
## 
## Residuals:
##      Min       1Q   Median       3Q      Max 
## -0.06971 -0.06510 -0.06336 -0.06195  0.95565 
## 
## Coefficients:
##               Estimate Std. Error t value Pr(>|t|)
## (Intercept) -2.918e+04  2.990e+04  -0.976    0.329
## year         4.385e+01  4.498e+01   0.975    0.330
## I(year^2)   -2.196e-02  2.255e-02  -0.974    0.330
## I(year^3)    3.665e-06  3.768e-06   0.973    0.331
## 
## Residual standard error: 0.2426 on 5046 degrees of freedom
## Multiple R-squared:  0.000414,   Adjusted R-squared:  -0.0001803 
## F-statistic: 0.6966 on 3 and 5046 DF,  p-value: 0.554
\end{verbatim}

\begin{Shaded}
\begin{Highlighting}[]
\NormalTok{lm5 =}\StringTok{ }\KeywordTok{lm}\NormalTok{(worry }\OperatorTok{~}\StringTok{ }\NormalTok{year }\OperatorTok{+}\StringTok{ }\KeywordTok{I}\NormalTok{(year}\OperatorTok{^}\DecValTok{2}\NormalTok{) }\OperatorTok{+}\StringTok{ }\KeywordTok{I}\NormalTok{(year}\OperatorTok{^}\DecValTok{3}\NormalTok{), sub, }\DataTypeTok{subset =}\NormalTok{ hiedu}\OperatorTok{==}\DecValTok{0}\NormalTok{)}
\KeywordTok{summary}\NormalTok{(lm5)}
\end{Highlighting}
\end{Shaded}

\begin{verbatim}
## 
## Call:
## lm(formula = worry ~ year + I(year^2) + I(year^3), data = sub, 
##     subset = hiedu == 0)
## 
## Residuals:
##     Min      1Q  Median      3Q     Max 
## -0.1790 -0.1292 -0.1189 -0.1127  0.8877 
## 
## Coefficients:
##               Estimate Std. Error t value Pr(>|t|)    
## (Intercept) -9.038e+04  2.412e+04  -3.747 0.000180 ***
## year         1.361e+02  3.629e+01   3.752 0.000176 ***
## I(year^2)   -6.835e-02  1.820e-02  -3.756 0.000173 ***
## I(year^3)    1.144e-05  3.042e-06   3.761 0.000170 ***
## ---
## Signif. codes:  0 '***' 0.001 '**' 0.01 '*' 0.05 '.' 0.1 ' ' 1
## 
## Residual standard error: 0.331 on 13690 degrees of freedom
## Multiple R-squared:  0.001963,   Adjusted R-squared:  0.001745 
## F-statistic: 8.977 on 3 and 13690 DF,  p-value: 6.163e-06
\end{verbatim}

Comparing people with different education levels, we can easily find out
that people with higher education level remain a more consistent
attitude toward their jobs, not worrying too much about being laid off,
while people with lower education became more pessimistic about their
jobs across time.

\hypertarget{try-a-complex-set-of-interactions}{%
\subsection{Try a complex set of
interactions}\label{try-a-complex-set-of-interactions}}

\begin{Shaded}
\begin{Highlighting}[]
\NormalTok{lm6 =}\StringTok{ }\KeywordTok{lm}\NormalTok{(worry }\OperatorTok{~}\StringTok{ }\NormalTok{year }\OperatorTok{+}\StringTok{ }\KeywordTok{I}\NormalTok{(year}\OperatorTok{^}\DecValTok{2}\NormalTok{) }\OperatorTok{+}\StringTok{ }\KeywordTok{I}\NormalTok{(year}\OperatorTok{^}\DecValTok{3}\NormalTok{) }\OperatorTok{+}\StringTok{ }\NormalTok{hiedu }\OperatorTok{+}\StringTok{ }\NormalTok{year}\OperatorTok{:}\NormalTok{hiedu }\OperatorTok{+}\StringTok{ }\KeywordTok{I}\NormalTok{(year}\OperatorTok{^}\DecValTok{2}\NormalTok{)}\OperatorTok{:}\NormalTok{hiedu }\OperatorTok{+}\StringTok{ }\KeywordTok{I}\NormalTok{(year}\OperatorTok{^}\DecValTok{3}\NormalTok{)}\OperatorTok{:}\NormalTok{hiedu, sub)}
\KeywordTok{summary}\NormalTok{(lm6)}
\end{Highlighting}
\end{Shaded}

\begin{verbatim}
## 
## Call:
## lm(formula = worry ~ year + I(year^2) + I(year^3) + hiedu + year:hiedu + 
##     I(year^2):hiedu + I(year^3):hiedu, data = sub)
## 
## Residuals:
##      Min       1Q   Median       3Q      Max 
## -0.17905 -0.12773 -0.11417 -0.06418  0.95565 
## 
## Coefficients:
##                   Estimate Std. Error t value Pr(>|t|)    
## (Intercept)     -9.038e+04  2.257e+04  -4.005 6.22e-05 ***
## year             1.361e+02  3.395e+01   4.010 6.09e-05 ***
## I(year^2)       -6.835e-02  1.703e-02  -4.015 5.97e-05 ***
## I(year^3)        1.144e-05  2.846e-06   4.020 5.85e-05 ***
## hiedu            6.120e+04  4.435e+04   1.380    0.168    
## year:hiedu      -9.229e+01  6.670e+01  -1.384    0.166    
## I(year^2):hiedu  4.640e-02  3.344e-02   1.387    0.165    
## I(year^3):hiedu -7.774e-06  5.589e-06  -1.391    0.164    
## ---
## Signif. codes:  0 '***' 0.001 '**' 0.01 '*' 0.05 '.' 0.1 ' ' 1
## 
## Residual standard error: 0.3097 on 18736 degrees of freedom
## Multiple R-squared:  0.009701,   Adjusted R-squared:  0.009331 
## F-statistic: 26.22 on 7 and 18736 DF,  p-value: < 2.2e-16
\end{verbatim}

The Adjusted Rsquared from this interaction model is 0.009701.

\hypertarget{compare-with-the-simple-model}{%
\subsection{Compare with the simple
model}\label{compare-with-the-simple-model}}

\begin{Shaded}
\begin{Highlighting}[]
\NormalTok{lm7 =}\StringTok{ }\KeywordTok{lm}\NormalTok{(worry }\OperatorTok{~}\StringTok{ }\NormalTok{year }\OperatorTok{+}\StringTok{ }\KeywordTok{I}\NormalTok{(year}\OperatorTok{^}\DecValTok{2}\NormalTok{) }\OperatorTok{+}\StringTok{ }\KeywordTok{I}\NormalTok{(year}\OperatorTok{^}\DecValTok{3}\NormalTok{) }\OperatorTok{+}\StringTok{ }\NormalTok{hiedu, sub)}
\KeywordTok{summary}\NormalTok{(lm7)}
\end{Highlighting}
\end{Shaded}

\begin{verbatim}
## 
## Call:
## lm(formula = worry ~ year + I(year^2) + I(year^3) + hiedu, data = sub)
## 
## Residuals:
##     Min      1Q  Median      3Q     Max 
## -0.1644 -0.1272 -0.1167 -0.0635  0.9515 
## 
## Coefficients:
##               Estimate Std. Error t value Pr(>|t|)    
## (Intercept) -7.064e+04  1.935e+04  -3.650 0.000263 ***
## year         1.064e+02  2.911e+01   3.654 0.000259 ***
## I(year^2)   -5.339e-02  1.460e-02  -3.658 0.000255 ***
## I(year^3)    8.933e-06  2.440e-06   3.661 0.000252 ***
## hiedu       -6.364e-02  5.123e-03 -12.423  < 2e-16 ***
## ---
## Signif. codes:  0 '***' 0.001 '**' 0.01 '*' 0.05 '.' 0.1 ' ' 1
## 
## Residual standard error: 0.3098 on 18739 degrees of freedom
## Multiple R-squared:  0.009273,   Adjusted R-squared:  0.009061 
## F-statistic: 43.85 on 4 and 18739 DF,  p-value: < 2.2e-16
\end{verbatim}

The Adjusted Rsquared from this model is 0.009273, lower than the
complex interaction model.

\hypertarget{using-annova-testing-to-examine-whether-adding-in-the-interactions-help-the-model-fit}{%
\subsection{Using annova testing to examine whether adding in the
interactions help the model
fit}\label{using-annova-testing-to-examine-whether-adding-in-the-interactions-help-the-model-fit}}

\begin{Shaded}
\begin{Highlighting}[]
\KeywordTok{anova}\NormalTok{(lm7,lm6)}
\end{Highlighting}
\end{Shaded}

\begin{verbatim}
## Analysis of Variance Table
## 
## Model 1: worry ~ year + I(year^2) + I(year^3) + hiedu
## Model 2: worry ~ year + I(year^2) + I(year^3) + hiedu + year:hiedu + I(year^2):hiedu + 
##     I(year^3):hiedu
##   Res.Df    RSS Df Sum of Sq      F  Pr(>F)  
## 1  18739 1798.0                              
## 2  18736 1797.2  3   0.77674 2.6991 0.04407 *
## ---
## Signif. codes:  0 '***' 0.001 '**' 0.01 '*' 0.05 '.' 0.1 ' ' 1
\end{verbatim}

The interaction model turns out to be better fit.


\end{document}
